In [46]:
import pandas as pd
from battleship_variables import barco_icon, agua_icon, shoot_icon



tabla=[["ðŸš£"," ","ðŸš¢"," ","ðŸŒŠ"," "," "],
       ["ðŸš£"," ","ðŸš¢"," "," "," "," "],
       ["ðŸš£"," ","ðŸš¢"," ","ðŸŒŠ"," "," "],
       ["ðŸš£","ðŸ’¥","ðŸš¢"," "," "," "," "],
       ["ðŸš£"," ","ðŸš¢","ðŸ’¥"," "," "," "],
       ["ðŸš£"," ","ðŸš¢"," "," "," "," "],
       [" "," "," "," "," "," "," "]]

mt = mostrar_tablero() # Create an instance of the mostrar_tablero class
 # Call the mostrar method on the instance and pass the tabla as an argument